apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.name }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.acme.server }}
    # Email address used for ACME registration
    email: {{ .Values.acme.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
     name: {{ .Values.acme.secretRef.name }}
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
       ingress:
         class:  nginx