controller:
  publishService:
    enabled: "true"
  config: # https://github.com/kubernetes/ingress-nginx/issues/3996
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    use-proxy-protocol: "true"
    proxy-buffer-size: "128k"
  metrics:
    enabled: true
  service:
    annotations: # https://github.com/kubernetes/ingress-nginx/issues/3996
      service.beta.kubernetes.io/do-loadbalancer-name: ${load_balancer_name}
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
      service.beta.kubernetes.io/do-loadbalancer-hostname: "${load_balancer_hostname}"
      kubernetes.digitalocean.com/load-balancer-id: ${load_balancer_id}
    loadBalancerIP: ${public_ip}
    externalTrafficPolicy: "Local"