name: infrastracture

on:
  push:
    branches:
      - "develop"

env:
  TF_FOLDER: "hello-world/live"
  BACKEND_ENDPOINT: "https://fra1.digitaloceanspaces.com"
  BACKEND_KEY: "workshop/live/terraform.tfstate"
  BACKEND_BUCKET: "workshoptfstate"
  BACKEND_REGION: "eu-central-1"
  BACKEND_ACCESS_KEY: ${{ secrets.DIGITALOCEAN_SPACE_ACCESS_KEY }}
  BACKEND_SECRET_KEY: ${{ secrets.DIGITALOCEAN_SPACE_SECRET_KEY }}
  TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN}}
  TF_VAR_ovh_application_key: ${{ secrets.OVH_APPLICATION_KEY }}
  TF_VAR_ovh_application_secret: ${{ secrets.OVH_APPLICATION_SECRET }}
  TF_VAR_ovh_consumer_key: ${{ secrets.OVH_CONSUMER_KEY }}

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: "GIT checkout"
        uses: actions/checkout@v3

      - name: TERRAFORM init
        working-directory: ${{ env.TF_FOLDER }}
        run: |
          terraform init -backend-config='endpoint="$BACKEND_ENDPOINT"' \
            -backend-config='key="$BACKEND_KEY"' \
            -backend-config='bucket="$BACKEND_BUCKET"' \
            -backend-config='eu-central-1="$BACKEND_REGION"' \
            -backend-config='access_key="$BACKEND_ACCESS_KEY"' \
            -backend-config='secret_key="$BACKEND_SECRET_KEY"' \
            -backend-config='skip_credentials_validation="true"' \
            -backend-config='skip_metadata_api_check="true"'

      - name: TERRAFORM validate
        working-directory: ${{ env.TF_FOLDER }}
        run: |
          terraform validate
      
      - name: TERRAFORM plan
        working-directory: ${{ env.TF_FOLDER }}
        run: |
          terraform plan
      
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        timeout-minutes: 60
        with:
          secret: ${{ github.TOKEN }}
          approvers: SupertrampR
          minimum-approvals: 1
          issue-title: "Check terraform plan generated by github action and decide whether to approve or cancel."
  
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: "GIT checkout"
        uses: actions/checkout@v3

      - name: TERRAFORM init
        working-directory: ${{ env.TF_FOLDER }}
        run: |
          terraform init -backend-config='endpoint="$BACKEND_ENDPOINT"' \
            -backend-config='key="$BACKEND_KEY"' \
            -backend-config='bucket="$BACKEND_BUCKET"' \
            -backend-config='eu-central-1="$BACKEND_REGION"' \
            -backend-config='access_key="$BACKEND_ACCESS_KEY"' \
            -backend-config='secret_key="$BACKEND_SECRET_KEY"' \
            -backend-config='skip_credentials_validation="true"' \
            -backend-config='skip_metadata_api_check="true"'

      - name: TERRAFORM apply
        working-directory: ${{ env.TF_FOLDER }}
        run: |
          terraform apply -auto-approve
